modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
#issueTrackerURL="" #optional

[[mods]]
    modId="replacer" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Redstone Replacer" #mandatory
    #updateJSONURL="" #optional
    #displayURL="" #optional
    #logoFile="" #optional
    #credits="" #optional
    authors="Dominic Cousins :: dalmposter" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description='''
    Allows you to force repeaters to consume suspicious looking cocaine and become replacers
    '''